/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author ssuaz
 */
public class MenuDeOpciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOpciones
     */
    public MenuDeOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddMember = new javax.swing.JButton();
        RegisterAffiliate = new javax.swing.JButton();
        RegisterPurchase = new javax.swing.JButton();
        PayBill = new javax.swing.JButton();
        IncreaseFunds = new javax.swing.JButton();
        ShowAffiliateAndItsMembers = new javax.swing.JButton();
        ShowMembers = new javax.swing.JButton();
        DeleteMember = new javax.swing.JButton();
        TextTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        AddMember.setText("Inscribir Miembro");
        AddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMemberMouseClicked(evt);
            }
        });
        AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMemberActionPerformed(evt);
            }
        });

        RegisterAffiliate.setText("Registrar Persona Autorizada");
        RegisterAffiliate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterAffiliateActionPerformed(evt);
            }
        });

        RegisterPurchase.setText("Registrar Compra");
        RegisterPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPurchaseActionPerformed(evt);
            }
        });

        PayBill.setText("Pagar Factura");
        PayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBillActionPerformed(evt);
            }
        });

        IncreaseFunds.setText("Aumentar Fondos");
        IncreaseFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseFundsActionPerformed(evt);
            }
        });

        ShowAffiliateAndItsMembers.setText("Mostrar Personas Autorizadas y sus Miembros");
        ShowAffiliateAndItsMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAffiliateAndItsMembersActionPerformed(evt);
            }
        });

        ShowMembers.setText("Mostrar Miembros");
        ShowMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMembersActionPerformed(evt);
            }
        });

        DeleteMember.setText("Eliminar Miembro");
        DeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMemberActionPerformed(evt);
            }
        });

        TextTitle.setBackground(new java.awt.Color(102, 102, 102));
        TextTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TextTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTitle.setText("MENU DE OPCIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(TextTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddMember)
                                .addGap(18, 18, 18)
                                .addComponent(PayBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(RegisterAffiliate))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(RegisterPurchase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ShowMembers)
                                .addGap(34, 34, 34)
                                .addComponent(DeleteMember))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ShowAffiliateAndItsMembers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IncreaseFunds)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterAffiliate)
                    .addComponent(PayBill)
                    .addComponent(AddMember))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowMembers)
                    .addComponent(DeleteMember)
                    .addComponent(RegisterPurchase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowAffiliateAndItsMembers)
                    .addComponent(IncreaseFunds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberActionPerformed
        AddMember a1 = new AddMember();
        a1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_AddMemberActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void AddMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMemberMouseClicked

    private void RegisterAffiliateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterAffiliateActionPerformed
        RegisterAffiliate ra1 = new RegisterAffiliate();
        ra1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_RegisterAffiliateActionPerformed

    private void RegisterPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPurchaseActionPerformed
        RegisterPurchase rp1 = new RegisterPurchase();
        rp1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_RegisterPurchaseActionPerformed

    private void ShowMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMembersActionPerformed
        ShowMembers sm1 = new ShowMembers();
        sm1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ShowMembersActionPerformed

    private void PayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBillActionPerformed
        PayBill pb1 = new PayBill();
        pb1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_PayBillActionPerformed

    private void DeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberActionPerformed
        DeleteMember dm1 = new DeleteMember();
        dm1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_DeleteMemberActionPerformed

    private void IncreaseFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseFundsActionPerformed
        IncreaseFunds if1 = new IncreaseFunds ();
        if1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_IncreaseFundsActionPerformed

    private void ShowAffiliateAndItsMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAffiliateAndItsMembersActionPerformed
        ShowAffiliateAndItsMembers sam1 = new ShowAffiliateAndItsMembers();
        sam1.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ShowAffiliateAndItsMembersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMember;
    private javax.swing.JButton DeleteMember;
    private javax.swing.JButton IncreaseFunds;
    private javax.swing.JButton PayBill;
    private javax.swing.JButton RegisterAffiliate;
    private javax.swing.JButton RegisterPurchase;
    private javax.swing.JButton ShowAffiliateAndItsMembers;
    private javax.swing.JButton ShowMembers;
    private javax.swing.JLabel TextTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
